export const actionTypes = {
  SET_ITEMS: "SET_ITEMS",
  SET_CART_ITEMS: "SET_CART_ITEMS",
  DEL_CART_ITEM: "DEL_CART_ITEM",
  ITEM_IS_REMOVED: "ITEM_IS_REMOVED",
  SET_FAVORITES: "SET_FAVORITES",
  GET_ORDER_ID: "GET_ORDER_ID",
  SET_ORDERS: "SET_ORDERS",
  SET_ORDER_STATUS: "SET_ORDER_STATUS",
  SET_SEARCH_VALUE: "SET_SEARCH_VALUE",
  CLEAR_INPUT_FIELD: "CLEAR_INPUT_FIELD",
  SET_TOGGLE_LOADING: "SET_TOGGLE_LOADING",
};